name: Mi Primer Automatización

# Evento: Se activa cada vez que subes cambios (push)
on: [push]

jobs:
  saludo-inicial:
    runs-on: ubuntu-latest
    steps:
      - name: Saludar en la consola
        run: echo "¡Felicidades! Tu primer GitHub Action funciona correctamente."
